package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AlarmRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.id
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.dataTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.isProcessed
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Integer isProcessed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.level
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.triggerId
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Long triggerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.alarmType
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private String alarmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.summary
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.createTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.lastUpdateTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.startTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.endTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_record.content
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm_record
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.id
     *
     * @return the value of alarm_record.id
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.id
     *
     * @param id the value for alarm_record.id
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.dataTime
     *
     * @return the value of alarm_record.dataTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.dataTime
     *
     * @param dataTime the value for alarm_record.dataTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.isProcessed
     *
     * @return the value of alarm_record.isProcessed
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Integer getIsProcessed() {
        return isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.isProcessed
     *
     * @param isProcessed the value for alarm_record.isProcessed
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setIsProcessed(Integer isProcessed) {
        this.isProcessed = isProcessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.level
     *
     * @return the value of alarm_record.level
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.level
     *
     * @param level the value for alarm_record.level
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.triggerId
     *
     * @return the value of alarm_record.triggerId
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Long getTriggerId() {
        return triggerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.triggerId
     *
     * @param triggerId the value for alarm_record.triggerId
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setTriggerId(Long triggerId) {
        this.triggerId = triggerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.alarmType
     *
     * @return the value of alarm_record.alarmType
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public String getAlarmType() {
        return alarmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.alarmType
     *
     * @param alarmType the value for alarm_record.alarmType
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType == null ? null : alarmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.summary
     *
     * @return the value of alarm_record.summary
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.summary
     *
     * @param summary the value for alarm_record.summary
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.createTime
     *
     * @return the value of alarm_record.createTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.createTime
     *
     * @param createTime the value for alarm_record.createTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.lastUpdateTime
     *
     * @return the value of alarm_record.lastUpdateTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.lastUpdateTime
     *
     * @param lastUpdateTime the value for alarm_record.lastUpdateTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.startTime
     *
     * @return the value of alarm_record.startTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.startTime
     *
     * @param startTime the value for alarm_record.startTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.endTime
     *
     * @return the value of alarm_record.endTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.endTime
     *
     * @param endTime the value for alarm_record.endTime
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_record.content
     *
     * @return the value of alarm_record.content
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_record.content
     *
     * @param content the value for alarm_record.content
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_record
     *
     * @mbg.generated Tue Sep 04 15:37:29 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dataTime=").append(dataTime);
        sb.append(", isProcessed=").append(isProcessed);
        sb.append(", level=").append(level);
        sb.append(", triggerId=").append(triggerId);
        sb.append(", alarmType=").append(alarmType);
        sb.append(", summary=").append(summary);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}