package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AsAlarmConstant implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.id
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.alarmId
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private Long alarmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.constIndex
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private Integer constIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.name
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.code
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.value
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.description
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.createTime
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_constant.lastUpdateTime
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.id
     *
     * @return the value of as_alarm_constant.id
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.id
     *
     * @param id the value for as_alarm_constant.id
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.alarmId
     *
     * @return the value of as_alarm_constant.alarmId
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public Long getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.alarmId
     *
     * @param alarmId the value for as_alarm_constant.alarmId
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setAlarmId(Long alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.constIndex
     *
     * @return the value of as_alarm_constant.constIndex
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public Integer getConstIndex() {
        return constIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.constIndex
     *
     * @param constIndex the value for as_alarm_constant.constIndex
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setConstIndex(Integer constIndex) {
        this.constIndex = constIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.name
     *
     * @return the value of as_alarm_constant.name
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.name
     *
     * @param name the value for as_alarm_constant.name
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.code
     *
     * @return the value of as_alarm_constant.code
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.code
     *
     * @param code the value for as_alarm_constant.code
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.value
     *
     * @return the value of as_alarm_constant.value
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.value
     *
     * @param value the value for as_alarm_constant.value
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.description
     *
     * @return the value of as_alarm_constant.description
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.description
     *
     * @param description the value for as_alarm_constant.description
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.createTime
     *
     * @return the value of as_alarm_constant.createTime
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.createTime
     *
     * @param createTime the value for as_alarm_constant.createTime
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_constant.lastUpdateTime
     *
     * @return the value of as_alarm_constant.lastUpdateTime
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_constant.lastUpdateTime
     *
     * @param lastUpdateTime the value for as_alarm_constant.lastUpdateTime
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", alarmId=").append(alarmId);
        sb.append(", constIndex=").append(constIndex);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", value=").append(value);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}