package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AsAlarmTriggerRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.id
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.alarmId
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Long alarmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.conditionId
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Long conditionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.runTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Date runTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.runEnv
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Byte runEnv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.costTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Integer costTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.context
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.infoTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String infoTrigger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.warningTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String warningTrigger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.errorTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String errorTrigger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.recoveryTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String recoveryTrigger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.recoveryMessage
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String recoveryMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.alarmMessage
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String alarmMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.notifyTypes
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private String notifyTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.createTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_trigger_record.lastUpdateTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_trigger_record
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.id
     *
     * @return the value of as_alarm_trigger_record.id
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.id
     *
     * @param id the value for as_alarm_trigger_record.id
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.alarmId
     *
     * @return the value of as_alarm_trigger_record.alarmId
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Long getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.alarmId
     *
     * @param alarmId the value for as_alarm_trigger_record.alarmId
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setAlarmId(Long alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.conditionId
     *
     * @return the value of as_alarm_trigger_record.conditionId
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Long getConditionId() {
        return conditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.conditionId
     *
     * @param conditionId the value for as_alarm_trigger_record.conditionId
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setConditionId(Long conditionId) {
        this.conditionId = conditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.runTime
     *
     * @return the value of as_alarm_trigger_record.runTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Date getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.runTime
     *
     * @param runTime the value for as_alarm_trigger_record.runTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setRunTime(Date runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.runEnv
     *
     * @return the value of as_alarm_trigger_record.runEnv
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Byte getRunEnv() {
        return runEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.runEnv
     *
     * @param runEnv the value for as_alarm_trigger_record.runEnv
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setRunEnv(Byte runEnv) {
        this.runEnv = runEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.costTime
     *
     * @return the value of as_alarm_trigger_record.costTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Integer getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.costTime
     *
     * @param costTime the value for as_alarm_trigger_record.costTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setCostTime(Integer costTime) {
        this.costTime = costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.context
     *
     * @return the value of as_alarm_trigger_record.context
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.context
     *
     * @param context the value for as_alarm_trigger_record.context
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.infoTrigger
     *
     * @return the value of as_alarm_trigger_record.infoTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getInfoTrigger() {
        return infoTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.infoTrigger
     *
     * @param infoTrigger the value for as_alarm_trigger_record.infoTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setInfoTrigger(String infoTrigger) {
        this.infoTrigger = infoTrigger == null ? null : infoTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.warningTrigger
     *
     * @return the value of as_alarm_trigger_record.warningTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getWarningTrigger() {
        return warningTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.warningTrigger
     *
     * @param warningTrigger the value for as_alarm_trigger_record.warningTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setWarningTrigger(String warningTrigger) {
        this.warningTrigger = warningTrigger == null ? null : warningTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.errorTrigger
     *
     * @return the value of as_alarm_trigger_record.errorTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getErrorTrigger() {
        return errorTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.errorTrigger
     *
     * @param errorTrigger the value for as_alarm_trigger_record.errorTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setErrorTrigger(String errorTrigger) {
        this.errorTrigger = errorTrigger == null ? null : errorTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.recoveryTrigger
     *
     * @return the value of as_alarm_trigger_record.recoveryTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getRecoveryTrigger() {
        return recoveryTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.recoveryTrigger
     *
     * @param recoveryTrigger the value for as_alarm_trigger_record.recoveryTrigger
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setRecoveryTrigger(String recoveryTrigger) {
        this.recoveryTrigger = recoveryTrigger == null ? null : recoveryTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.recoveryMessage
     *
     * @return the value of as_alarm_trigger_record.recoveryMessage
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getRecoveryMessage() {
        return recoveryMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.recoveryMessage
     *
     * @param recoveryMessage the value for as_alarm_trigger_record.recoveryMessage
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setRecoveryMessage(String recoveryMessage) {
        this.recoveryMessage = recoveryMessage == null ? null : recoveryMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.alarmMessage
     *
     * @return the value of as_alarm_trigger_record.alarmMessage
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getAlarmMessage() {
        return alarmMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.alarmMessage
     *
     * @param alarmMessage the value for as_alarm_trigger_record.alarmMessage
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setAlarmMessage(String alarmMessage) {
        this.alarmMessage = alarmMessage == null ? null : alarmMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.notifyTypes
     *
     * @return the value of as_alarm_trigger_record.notifyTypes
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public String getNotifyTypes() {
        return notifyTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.notifyTypes
     *
     * @param notifyTypes the value for as_alarm_trigger_record.notifyTypes
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setNotifyTypes(String notifyTypes) {
        this.notifyTypes = notifyTypes == null ? null : notifyTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.createTime
     *
     * @return the value of as_alarm_trigger_record.createTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.createTime
     *
     * @param createTime the value for as_alarm_trigger_record.createTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_trigger_record.lastUpdateTime
     *
     * @return the value of as_alarm_trigger_record.lastUpdateTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_trigger_record.lastUpdateTime
     *
     * @param lastUpdateTime the value for as_alarm_trigger_record.lastUpdateTime
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger_record
     *
     * @mbg.generated Tue Jul 24 09:53:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", alarmId=").append(alarmId);
        sb.append(", conditionId=").append(conditionId);
        sb.append(", runTime=").append(runTime);
        sb.append(", runEnv=").append(runEnv);
        sb.append(", costTime=").append(costTime);
        sb.append(", context=").append(context);
        sb.append(", infoTrigger=").append(infoTrigger);
        sb.append(", warningTrigger=").append(warningTrigger);
        sb.append(", errorTrigger=").append(errorTrigger);
        sb.append(", recoveryTrigger=").append(recoveryTrigger);
        sb.append(", recoveryMessage=").append(recoveryMessage);
        sb.append(", alarmMessage=").append(alarmMessage);
        sb.append(", notifyTypes=").append(notifyTypes);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}