package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AsAlarmMsg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_msg.id
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_msg.alarmId
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    private Long alarmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_msg.createTime
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_alarm_msg.lastUpdateTime
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_msg.id
     *
     * @return the value of as_alarm_msg.id
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_msg.id
     *
     * @param id the value for as_alarm_msg.id
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_msg.alarmId
     *
     * @return the value of as_alarm_msg.alarmId
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public Long getAlarmId() {
        return alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_msg.alarmId
     *
     * @param alarmId the value for as_alarm_msg.alarmId
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setAlarmId(Long alarmId) {
        this.alarmId = alarmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_msg.createTime
     *
     * @return the value of as_alarm_msg.createTime
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_msg.createTime
     *
     * @param createTime the value for as_alarm_msg.createTime
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_alarm_msg.lastUpdateTime
     *
     * @return the value of as_alarm_msg.lastUpdateTime
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_alarm_msg.lastUpdateTime
     *
     * @param lastUpdateTime the value for as_alarm_msg.lastUpdateTime
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", alarmId=").append(alarmId);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}