package com.treefinance.saas.monitor.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AsAlarmTriggerCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected int limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected int offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public AsAlarmTriggerCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setLimit(int limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setOffset(int offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAlarmIdIsNull() {
            addCriterion("alarmId is null");
            return (Criteria) this;
        }

        public Criteria andAlarmIdIsNotNull() {
            addCriterion("alarmId is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmIdEqualTo(Long value) {
            addCriterion("alarmId =", value, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdNotEqualTo(Long value) {
            addCriterion("alarmId <>", value, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdGreaterThan(Long value) {
            addCriterion("alarmId >", value, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdGreaterThanOrEqualTo(Long value) {
            addCriterion("alarmId >=", value, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdLessThan(Long value) {
            addCriterion("alarmId <", value, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdLessThanOrEqualTo(Long value) {
            addCriterion("alarmId <=", value, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdIn(List<Long> values) {
            addCriterion("alarmId in", values, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdNotIn(List<Long> values) {
            addCriterion("alarmId not in", values, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdBetween(Long value1, Long value2) {
            addCriterion("alarmId between", value1, value2, "alarmId");
            return (Criteria) this;
        }

        public Criteria andAlarmIdNotBetween(Long value1, Long value2) {
            addCriterion("alarmId not between", value1, value2, "alarmId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerIsNull() {
            addCriterion("infoTrigger is null");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerIsNotNull() {
            addCriterion("infoTrigger is not null");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerEqualTo(String value) {
            addCriterion("infoTrigger =", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerNotEqualTo(String value) {
            addCriterion("infoTrigger <>", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerGreaterThan(String value) {
            addCriterion("infoTrigger >", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerGreaterThanOrEqualTo(String value) {
            addCriterion("infoTrigger >=", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerLessThan(String value) {
            addCriterion("infoTrigger <", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerLessThanOrEqualTo(String value) {
            addCriterion("infoTrigger <=", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerLike(String value) {
            addCriterion("infoTrigger like", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerNotLike(String value) {
            addCriterion("infoTrigger not like", value, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerIn(List<String> values) {
            addCriterion("infoTrigger in", values, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerNotIn(List<String> values) {
            addCriterion("infoTrigger not in", values, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerBetween(String value1, String value2) {
            addCriterion("infoTrigger between", value1, value2, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andInfoTriggerNotBetween(String value1, String value2) {
            addCriterion("infoTrigger not between", value1, value2, "infoTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerIsNull() {
            addCriterion("warningTrigger is null");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerIsNotNull() {
            addCriterion("warningTrigger is not null");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerEqualTo(String value) {
            addCriterion("warningTrigger =", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerNotEqualTo(String value) {
            addCriterion("warningTrigger <>", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerGreaterThan(String value) {
            addCriterion("warningTrigger >", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerGreaterThanOrEqualTo(String value) {
            addCriterion("warningTrigger >=", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerLessThan(String value) {
            addCriterion("warningTrigger <", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerLessThanOrEqualTo(String value) {
            addCriterion("warningTrigger <=", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerLike(String value) {
            addCriterion("warningTrigger like", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerNotLike(String value) {
            addCriterion("warningTrigger not like", value, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerIn(List<String> values) {
            addCriterion("warningTrigger in", values, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerNotIn(List<String> values) {
            addCriterion("warningTrigger not in", values, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerBetween(String value1, String value2) {
            addCriterion("warningTrigger between", value1, value2, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andWarningTriggerNotBetween(String value1, String value2) {
            addCriterion("warningTrigger not between", value1, value2, "warningTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerIsNull() {
            addCriterion("errorTrigger is null");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerIsNotNull() {
            addCriterion("errorTrigger is not null");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerEqualTo(String value) {
            addCriterion("errorTrigger =", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerNotEqualTo(String value) {
            addCriterion("errorTrigger <>", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerGreaterThan(String value) {
            addCriterion("errorTrigger >", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerGreaterThanOrEqualTo(String value) {
            addCriterion("errorTrigger >=", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerLessThan(String value) {
            addCriterion("errorTrigger <", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerLessThanOrEqualTo(String value) {
            addCriterion("errorTrigger <=", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerLike(String value) {
            addCriterion("errorTrigger like", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerNotLike(String value) {
            addCriterion("errorTrigger not like", value, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerIn(List<String> values) {
            addCriterion("errorTrigger in", values, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerNotIn(List<String> values) {
            addCriterion("errorTrigger not in", values, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerBetween(String value1, String value2) {
            addCriterion("errorTrigger between", value1, value2, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andErrorTriggerNotBetween(String value1, String value2) {
            addCriterion("errorTrigger not between", value1, value2, "errorTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerIsNull() {
            addCriterion("recoveryTrigger is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerIsNotNull() {
            addCriterion("recoveryTrigger is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerEqualTo(String value) {
            addCriterion("recoveryTrigger =", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerNotEqualTo(String value) {
            addCriterion("recoveryTrigger <>", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerGreaterThan(String value) {
            addCriterion("recoveryTrigger >", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerGreaterThanOrEqualTo(String value) {
            addCriterion("recoveryTrigger >=", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerLessThan(String value) {
            addCriterion("recoveryTrigger <", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerLessThanOrEqualTo(String value) {
            addCriterion("recoveryTrigger <=", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerLike(String value) {
            addCriterion("recoveryTrigger like", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerNotLike(String value) {
            addCriterion("recoveryTrigger not like", value, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerIn(List<String> values) {
            addCriterion("recoveryTrigger in", values, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerNotIn(List<String> values) {
            addCriterion("recoveryTrigger not in", values, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerBetween(String value1, String value2) {
            addCriterion("recoveryTrigger between", value1, value2, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryTriggerNotBetween(String value1, String value2) {
            addCriterion("recoveryTrigger not between", value1, value2, "recoveryTrigger");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateIsNull() {
            addCriterion("recoveryMessageTemplate is null");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateIsNotNull() {
            addCriterion("recoveryMessageTemplate is not null");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateEqualTo(String value) {
            addCriterion("recoveryMessageTemplate =", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateNotEqualTo(String value) {
            addCriterion("recoveryMessageTemplate <>", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateGreaterThan(String value) {
            addCriterion("recoveryMessageTemplate >", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateGreaterThanOrEqualTo(String value) {
            addCriterion("recoveryMessageTemplate >=", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateLessThan(String value) {
            addCriterion("recoveryMessageTemplate <", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateLessThanOrEqualTo(String value) {
            addCriterion("recoveryMessageTemplate <=", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateLike(String value) {
            addCriterion("recoveryMessageTemplate like", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateNotLike(String value) {
            addCriterion("recoveryMessageTemplate not like", value, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateIn(List<String> values) {
            addCriterion("recoveryMessageTemplate in", values, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateNotIn(List<String> values) {
            addCriterion("recoveryMessageTemplate not in", values, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateBetween(String value1, String value2) {
            addCriterion("recoveryMessageTemplate between", value1, value2, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andRecoveryMessageTemplateNotBetween(String value1, String value2) {
            addCriterion("recoveryMessageTemplate not between", value1, value2, "recoveryMessageTemplate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("lastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("lastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("lastUpdateTime =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("lastUpdateTime <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("lastUpdateTime >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("lastUpdateTime <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("lastUpdateTime <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("lastUpdateTime in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("lastUpdateTime not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("lastUpdateTime not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 18 19:57:44 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}