package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AsBasicDataHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data_history.id
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data_history.basicDataId
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private Long basicDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data_history.basicDataCode
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private String basicDataCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data_history.dataId
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private String dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data_history.dataTime
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data_history.dataJson
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private String dataJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_basic_data_history
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data_history.id
     *
     * @return the value of as_basic_data_history.id
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data_history.id
     *
     * @param id the value for as_basic_data_history.id
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data_history.basicDataId
     *
     * @return the value of as_basic_data_history.basicDataId
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public Long getBasicDataId() {
        return basicDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data_history.basicDataId
     *
     * @param basicDataId the value for as_basic_data_history.basicDataId
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public void setBasicDataId(Long basicDataId) {
        this.basicDataId = basicDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data_history.basicDataCode
     *
     * @return the value of as_basic_data_history.basicDataCode
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public String getBasicDataCode() {
        return basicDataCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data_history.basicDataCode
     *
     * @param basicDataCode the value for as_basic_data_history.basicDataCode
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public void setBasicDataCode(String basicDataCode) {
        this.basicDataCode = basicDataCode == null ? null : basicDataCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data_history.dataId
     *
     * @return the value of as_basic_data_history.dataId
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data_history.dataId
     *
     * @param dataId the value for as_basic_data_history.dataId
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data_history.dataTime
     *
     * @return the value of as_basic_data_history.dataTime
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data_history.dataTime
     *
     * @param dataTime the value for as_basic_data_history.dataTime
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data_history.dataJson
     *
     * @return the value of as_basic_data_history.dataJson
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public String getDataJson() {
        return dataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data_history.dataJson
     *
     * @param dataJson the value for as_basic_data_history.dataJson
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    public void setDataJson(String dataJson) {
        this.dataJson = dataJson == null ? null : dataJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data_history
     *
     * @mbg.generated Mon May 21 17:33:31 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", basicDataId=").append(basicDataId);
        sb.append(", basicDataCode=").append(basicDataCode);
        sb.append(", dataId=").append(dataId);
        sb.append(", dataTime=").append(dataTime);
        sb.append(", dataJson=").append(dataJson);
        sb.append("]");
        return sb.toString();
    }
}