package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class BasicData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.id
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.dataCode
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private String dataCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.dataName
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private String dataName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.dataJson
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private String dataJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.dataSource
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private Byte dataSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.dataSourceConfigJson
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private String dataSourceConfigJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.createTime
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_basic_data.lastUpdateTime
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_basic_data
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.id
     *
     * @return the value of as_basic_data.id
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.id
     *
     * @param id the value for as_basic_data.id
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.dataCode
     *
     * @return the value of as_basic_data.dataCode
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public String getDataCode() {
        return dataCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.dataCode
     *
     * @param dataCode the value for as_basic_data.dataCode
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setDataCode(String dataCode) {
        this.dataCode = dataCode == null ? null : dataCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.dataName
     *
     * @return the value of as_basic_data.dataName
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.dataName
     *
     * @param dataName the value for as_basic_data.dataName
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setDataName(String dataName) {
        this.dataName = dataName == null ? null : dataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.dataJson
     *
     * @return the value of as_basic_data.dataJson
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public String getDataJson() {
        return dataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.dataJson
     *
     * @param dataJson the value for as_basic_data.dataJson
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setDataJson(String dataJson) {
        this.dataJson = dataJson == null ? null : dataJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.dataSource
     *
     * @return the value of as_basic_data.dataSource
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public Byte getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.dataSource
     *
     * @param dataSource the value for as_basic_data.dataSource
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setDataSource(Byte dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.dataSourceConfigJson
     *
     * @return the value of as_basic_data.dataSourceConfigJson
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public String getDataSourceConfigJson() {
        return dataSourceConfigJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.dataSourceConfigJson
     *
     * @param dataSourceConfigJson the value for as_basic_data.dataSourceConfigJson
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setDataSourceConfigJson(String dataSourceConfigJson) {
        this.dataSourceConfigJson = dataSourceConfigJson == null ? null : dataSourceConfigJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.createTime
     *
     * @return the value of as_basic_data.createTime
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.createTime
     *
     * @param createTime the value for as_basic_data.createTime
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_basic_data.lastUpdateTime
     *
     * @return the value of as_basic_data.lastUpdateTime
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_basic_data.lastUpdateTime
     *
     * @param lastUpdateTime the value for as_basic_data.lastUpdateTime
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dataCode=").append(dataCode);
        sb.append(", dataName=").append(dataName);
        sb.append(", dataJson=").append(dataJson);
        sb.append(", dataSource=").append(dataSource);
        sb.append(", dataSourceConfigJson=").append(dataSourceConfigJson);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}