package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Operator implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.Id
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.WebsiteId
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private Integer websiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.OperatorName
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.region
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.IsEnabled
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private String isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.CreatedAt
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operator.UpdatedAt
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.Id
     *
     * @return the value of t_operator.Id
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.Id
     *
     * @param id the value for t_operator.Id
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.WebsiteId
     *
     * @return the value of t_operator.WebsiteId
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.WebsiteId
     *
     * @param websiteId the value for t_operator.WebsiteId
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.OperatorName
     *
     * @return the value of t_operator.OperatorName
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.OperatorName
     *
     * @param operatorName the value for t_operator.OperatorName
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.region
     *
     * @return the value of t_operator.region
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.region
     *
     * @param region the value for t_operator.region
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.IsEnabled
     *
     * @return the value of t_operator.IsEnabled
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.IsEnabled
     *
     * @param isEnabled the value for t_operator.IsEnabled
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled == null ? null : isEnabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.CreatedAt
     *
     * @return the value of t_operator.CreatedAt
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.CreatedAt
     *
     * @param createdAt the value for t_operator.CreatedAt
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operator.UpdatedAt
     *
     * @return the value of t_operator.UpdatedAt
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operator.UpdatedAt
     *
     * @param updatedAt the value for t_operator.UpdatedAt
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", websiteId=").append(websiteId);
        sb.append(", operatorName=").append(operatorName);
        sb.append(", region=").append(region);
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }
}