package com.treefinance.saas.monitor.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class StatTemplate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.id
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.templateCode
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private String templateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.templateName
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.status
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.statCron
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private String statCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.expressionType
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Integer expressionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.basicDataId
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Long basicDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.basicDataFilter
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private String basicDataFilter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.dataObject
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private String dataObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.effectiveTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Integer effectiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.flushDataCron
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private String flushDataCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.createTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_stat_template.lastUpdateTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table as_stat_template
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.id
     *
     * @return the value of as_stat_template.id
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.id
     *
     * @param id the value for as_stat_template.id
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.templateCode
     *
     * @return the value of as_stat_template.templateCode
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.templateCode
     *
     * @param templateCode the value for as_stat_template.templateCode
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode == null ? null : templateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.templateName
     *
     * @return the value of as_stat_template.templateName
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.templateName
     *
     * @param templateName the value for as_stat_template.templateName
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.status
     *
     * @return the value of as_stat_template.status
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.status
     *
     * @param status the value for as_stat_template.status
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.statCron
     *
     * @return the value of as_stat_template.statCron
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public String getStatCron() {
        return statCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.statCron
     *
     * @param statCron the value for as_stat_template.statCron
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setStatCron(String statCron) {
        this.statCron = statCron == null ? null : statCron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.expressionType
     *
     * @return the value of as_stat_template.expressionType
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Integer getExpressionType() {
        return expressionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.expressionType
     *
     * @param expressionType the value for as_stat_template.expressionType
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setExpressionType(Integer expressionType) {
        this.expressionType = expressionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.basicDataId
     *
     * @return the value of as_stat_template.basicDataId
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Long getBasicDataId() {
        return basicDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.basicDataId
     *
     * @param basicDataId the value for as_stat_template.basicDataId
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setBasicDataId(Long basicDataId) {
        this.basicDataId = basicDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.basicDataFilter
     *
     * @return the value of as_stat_template.basicDataFilter
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public String getBasicDataFilter() {
        return basicDataFilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.basicDataFilter
     *
     * @param basicDataFilter the value for as_stat_template.basicDataFilter
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setBasicDataFilter(String basicDataFilter) {
        this.basicDataFilter = basicDataFilter == null ? null : basicDataFilter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.dataObject
     *
     * @return the value of as_stat_template.dataObject
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public String getDataObject() {
        return dataObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.dataObject
     *
     * @param dataObject the value for as_stat_template.dataObject
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setDataObject(String dataObject) {
        this.dataObject = dataObject == null ? null : dataObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.effectiveTime
     *
     * @return the value of as_stat_template.effectiveTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Integer getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.effectiveTime
     *
     * @param effectiveTime the value for as_stat_template.effectiveTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setEffectiveTime(Integer effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.flushDataCron
     *
     * @return the value of as_stat_template.flushDataCron
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public String getFlushDataCron() {
        return flushDataCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.flushDataCron
     *
     * @param flushDataCron the value for as_stat_template.flushDataCron
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setFlushDataCron(String flushDataCron) {
        this.flushDataCron = flushDataCron == null ? null : flushDataCron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.createTime
     *
     * @return the value of as_stat_template.createTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.createTime
     *
     * @param createTime the value for as_stat_template.createTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_stat_template.lastUpdateTime
     *
     * @return the value of as_stat_template.lastUpdateTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_stat_template.lastUpdateTime
     *
     * @param lastUpdateTime the value for as_stat_template.lastUpdateTime
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Thu Apr 26 10:25:03 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", templateCode=").append(templateCode);
        sb.append(", templateName=").append(templateName);
        sb.append(", status=").append(status);
        sb.append(", statCron=").append(statCron);
        sb.append(", expressionType=").append(expressionType);
        sb.append(", basicDataId=").append(basicDataId);
        sb.append(", basicDataFilter=").append(basicDataFilter);
        sb.append(", dataObject=").append(dataObject);
        sb.append(", effectiveTime=").append(effectiveTime);
        sb.append(", flushDataCron=").append(flushDataCron);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}