package com.treefinance.saas.monitor.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WebsiteCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public WebsiteCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeIsNull() {
            addCriterion("WebsiteType is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeIsNotNull() {
            addCriterion("WebsiteType is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeEqualTo(String value) {
            addCriterion("WebsiteType =", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeNotEqualTo(String value) {
            addCriterion("WebsiteType <>", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeGreaterThan(String value) {
            addCriterion("WebsiteType >", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeGreaterThanOrEqualTo(String value) {
            addCriterion("WebsiteType >=", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeLessThan(String value) {
            addCriterion("WebsiteType <", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeLessThanOrEqualTo(String value) {
            addCriterion("WebsiteType <=", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeLike(String value) {
            addCriterion("WebsiteType like", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeNotLike(String value) {
            addCriterion("WebsiteType not like", value, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeIn(List<String> values) {
            addCriterion("WebsiteType in", values, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeNotIn(List<String> values) {
            addCriterion("WebsiteType not in", values, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeBetween(String value1, String value2) {
            addCriterion("WebsiteType between", value1, value2, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteTypeNotBetween(String value1, String value2) {
            addCriterion("WebsiteType not between", value1, value2, "websiteType");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameIsNull() {
            addCriterion("WebsiteName is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameIsNotNull() {
            addCriterion("WebsiteName is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameEqualTo(String value) {
            addCriterion("WebsiteName =", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameNotEqualTo(String value) {
            addCriterion("WebsiteName <>", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameGreaterThan(String value) {
            addCriterion("WebsiteName >", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameGreaterThanOrEqualTo(String value) {
            addCriterion("WebsiteName >=", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameLessThan(String value) {
            addCriterion("WebsiteName <", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameLessThanOrEqualTo(String value) {
            addCriterion("WebsiteName <=", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameLike(String value) {
            addCriterion("WebsiteName like", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameNotLike(String value) {
            addCriterion("WebsiteName not like", value, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameIn(List<String> values) {
            addCriterion("WebsiteName in", values, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameNotIn(List<String> values) {
            addCriterion("WebsiteName not in", values, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameBetween(String value1, String value2) {
            addCriterion("WebsiteName between", value1, value2, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteNameNotBetween(String value1, String value2) {
            addCriterion("WebsiteName not between", value1, value2, "websiteName");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainIsNull() {
            addCriterion("WebsiteDomain is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainIsNotNull() {
            addCriterion("WebsiteDomain is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainEqualTo(String value) {
            addCriterion("WebsiteDomain =", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainNotEqualTo(String value) {
            addCriterion("WebsiteDomain <>", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainGreaterThan(String value) {
            addCriterion("WebsiteDomain >", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainGreaterThanOrEqualTo(String value) {
            addCriterion("WebsiteDomain >=", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainLessThan(String value) {
            addCriterion("WebsiteDomain <", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainLessThanOrEqualTo(String value) {
            addCriterion("WebsiteDomain <=", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainLike(String value) {
            addCriterion("WebsiteDomain like", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainNotLike(String value) {
            addCriterion("WebsiteDomain not like", value, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainIn(List<String> values) {
            addCriterion("WebsiteDomain in", values, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainNotIn(List<String> values) {
            addCriterion("WebsiteDomain not in", values, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainBetween(String value1, String value2) {
            addCriterion("WebsiteDomain between", value1, value2, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andWebsiteDomainNotBetween(String value1, String value2) {
            addCriterion("WebsiteDomain not between", value1, value2, "websiteDomain");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNull() {
            addCriterion("IsEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIsNotNull() {
            addCriterion("IsEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnabledEqualTo(String value) {
            addCriterion("IsEnabled =", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotEqualTo(String value) {
            addCriterion("IsEnabled <>", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThan(String value) {
            addCriterion("IsEnabled >", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("IsEnabled >=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThan(String value) {
            addCriterion("IsEnabled <", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLessThanOrEqualTo(String value) {
            addCriterion("IsEnabled <=", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledLike(String value) {
            addCriterion("IsEnabled like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotLike(String value) {
            addCriterion("IsEnabled not like", value, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledIn(List<String> values) {
            addCriterion("IsEnabled in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotIn(List<String> values) {
            addCriterion("IsEnabled not in", values, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledBetween(String value1, String value2) {
            addCriterion("IsEnabled between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andIsEnabledNotBetween(String value1, String value2) {
            addCriterion("IsEnabled not between", value1, value2, "isEnabled");
            return (Criteria) this;
        }

        public Criteria andLoginTipIsNull() {
            addCriterion("LoginTip is null");
            return (Criteria) this;
        }

        public Criteria andLoginTipIsNotNull() {
            addCriterion("LoginTip is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTipEqualTo(String value) {
            addCriterion("LoginTip =", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipNotEqualTo(String value) {
            addCriterion("LoginTip <>", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipGreaterThan(String value) {
            addCriterion("LoginTip >", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipGreaterThanOrEqualTo(String value) {
            addCriterion("LoginTip >=", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipLessThan(String value) {
            addCriterion("LoginTip <", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipLessThanOrEqualTo(String value) {
            addCriterion("LoginTip <=", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipLike(String value) {
            addCriterion("LoginTip like", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipNotLike(String value) {
            addCriterion("LoginTip not like", value, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipIn(List<String> values) {
            addCriterion("LoginTip in", values, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipNotIn(List<String> values) {
            addCriterion("LoginTip not in", values, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipBetween(String value1, String value2) {
            addCriterion("LoginTip between", value1, value2, "loginTip");
            return (Criteria) this;
        }

        public Criteria andLoginTipNotBetween(String value1, String value2) {
            addCriterion("LoginTip not between", value1, value2, "loginTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipIsNull() {
            addCriterion("VerifyTip is null");
            return (Criteria) this;
        }

        public Criteria andVerifyTipIsNotNull() {
            addCriterion("VerifyTip is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyTipEqualTo(String value) {
            addCriterion("VerifyTip =", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipNotEqualTo(String value) {
            addCriterion("VerifyTip <>", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipGreaterThan(String value) {
            addCriterion("VerifyTip >", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipGreaterThanOrEqualTo(String value) {
            addCriterion("VerifyTip >=", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipLessThan(String value) {
            addCriterion("VerifyTip <", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipLessThanOrEqualTo(String value) {
            addCriterion("VerifyTip <=", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipLike(String value) {
            addCriterion("VerifyTip like", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipNotLike(String value) {
            addCriterion("VerifyTip not like", value, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipIn(List<String> values) {
            addCriterion("VerifyTip in", values, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipNotIn(List<String> values) {
            addCriterion("VerifyTip not in", values, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipBetween(String value1, String value2) {
            addCriterion("VerifyTip between", value1, value2, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andVerifyTipNotBetween(String value1, String value2) {
            addCriterion("VerifyTip not between", value1, value2, "verifyTip");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutIsNull() {
            addCriterion("InitTimeout is null");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutIsNotNull() {
            addCriterion("InitTimeout is not null");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutEqualTo(Integer value) {
            addCriterion("InitTimeout =", value, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutNotEqualTo(Integer value) {
            addCriterion("InitTimeout <>", value, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutGreaterThan(Integer value) {
            addCriterion("InitTimeout >", value, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("InitTimeout >=", value, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutLessThan(Integer value) {
            addCriterion("InitTimeout <", value, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("InitTimeout <=", value, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutIn(List<Integer> values) {
            addCriterion("InitTimeout in", values, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutNotIn(List<Integer> values) {
            addCriterion("InitTimeout not in", values, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("InitTimeout between", value1, value2, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andInitTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("InitTimeout not between", value1, value2, "initTimeout");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeIsNull() {
            addCriterion("CodeWaitTime is null");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeIsNotNull() {
            addCriterion("CodeWaitTime is not null");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeEqualTo(Integer value) {
            addCriterion("CodeWaitTime =", value, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeNotEqualTo(Integer value) {
            addCriterion("CodeWaitTime <>", value, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeGreaterThan(Integer value) {
            addCriterion("CodeWaitTime >", value, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CodeWaitTime >=", value, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeLessThan(Integer value) {
            addCriterion("CodeWaitTime <", value, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeLessThanOrEqualTo(Integer value) {
            addCriterion("CodeWaitTime <=", value, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeIn(List<Integer> values) {
            addCriterion("CodeWaitTime in", values, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeNotIn(List<Integer> values) {
            addCriterion("CodeWaitTime not in", values, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeBetween(Integer value1, Integer value2) {
            addCriterion("CodeWaitTime between", value1, value2, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andCodeWaitTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("CodeWaitTime not between", value1, value2, "codeWaitTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutIsNull() {
            addCriterion("LoginTimeout is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutIsNotNull() {
            addCriterion("LoginTimeout is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutEqualTo(Integer value) {
            addCriterion("LoginTimeout =", value, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutNotEqualTo(Integer value) {
            addCriterion("LoginTimeout <>", value, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutGreaterThan(Integer value) {
            addCriterion("LoginTimeout >", value, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutGreaterThanOrEqualTo(Integer value) {
            addCriterion("LoginTimeout >=", value, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutLessThan(Integer value) {
            addCriterion("LoginTimeout <", value, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutLessThanOrEqualTo(Integer value) {
            addCriterion("LoginTimeout <=", value, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutIn(List<Integer> values) {
            addCriterion("LoginTimeout in", values, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutNotIn(List<Integer> values) {
            addCriterion("LoginTimeout not in", values, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutBetween(Integer value1, Integer value2) {
            addCriterion("LoginTimeout between", value1, value2, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andLoginTimeoutNotBetween(Integer value1, Integer value2) {
            addCriterion("LoginTimeout not between", value1, value2, "loginTimeout");
            return (Criteria) this;
        }

        public Criteria andResetTypeIsNull() {
            addCriterion("ResetType is null");
            return (Criteria) this;
        }

        public Criteria andResetTypeIsNotNull() {
            addCriterion("ResetType is not null");
            return (Criteria) this;
        }

        public Criteria andResetTypeEqualTo(String value) {
            addCriterion("ResetType =", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeNotEqualTo(String value) {
            addCriterion("ResetType <>", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeGreaterThan(String value) {
            addCriterion("ResetType >", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ResetType >=", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeLessThan(String value) {
            addCriterion("ResetType <", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeLessThanOrEqualTo(String value) {
            addCriterion("ResetType <=", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeLike(String value) {
            addCriterion("ResetType like", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeNotLike(String value) {
            addCriterion("ResetType not like", value, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeIn(List<String> values) {
            addCriterion("ResetType in", values, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeNotIn(List<String> values) {
            addCriterion("ResetType not in", values, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeBetween(String value1, String value2) {
            addCriterion("ResetType between", value1, value2, "resetType");
            return (Criteria) this;
        }

        public Criteria andResetTypeNotBetween(String value1, String value2) {
            addCriterion("ResetType not between", value1, value2, "resetType");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateIsNull() {
            addCriterion("SmsTemplate is null");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateIsNotNull() {
            addCriterion("SmsTemplate is not null");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateEqualTo(String value) {
            addCriterion("SmsTemplate =", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateNotEqualTo(String value) {
            addCriterion("SmsTemplate <>", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateGreaterThan(String value) {
            addCriterion("SmsTemplate >", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateGreaterThanOrEqualTo(String value) {
            addCriterion("SmsTemplate >=", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateLessThan(String value) {
            addCriterion("SmsTemplate <", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateLessThanOrEqualTo(String value) {
            addCriterion("SmsTemplate <=", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateLike(String value) {
            addCriterion("SmsTemplate like", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateNotLike(String value) {
            addCriterion("SmsTemplate not like", value, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateIn(List<String> values) {
            addCriterion("SmsTemplate in", values, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateNotIn(List<String> values) {
            addCriterion("SmsTemplate not in", values, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateBetween(String value1, String value2) {
            addCriterion("SmsTemplate between", value1, value2, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsTemplateNotBetween(String value1, String value2) {
            addCriterion("SmsTemplate not between", value1, value2, "smsTemplate");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverIsNull() {
            addCriterion("SmsReceiver is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverIsNotNull() {
            addCriterion("SmsReceiver is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverEqualTo(String value) {
            addCriterion("SmsReceiver =", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverNotEqualTo(String value) {
            addCriterion("SmsReceiver <>", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverGreaterThan(String value) {
            addCriterion("SmsReceiver >", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverGreaterThanOrEqualTo(String value) {
            addCriterion("SmsReceiver >=", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverLessThan(String value) {
            addCriterion("SmsReceiver <", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverLessThanOrEqualTo(String value) {
            addCriterion("SmsReceiver <=", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverLike(String value) {
            addCriterion("SmsReceiver like", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverNotLike(String value) {
            addCriterion("SmsReceiver not like", value, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverIn(List<String> values) {
            addCriterion("SmsReceiver in", values, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverNotIn(List<String> values) {
            addCriterion("SmsReceiver not in", values, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverBetween(String value1, String value2) {
            addCriterion("SmsReceiver between", value1, value2, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andSmsReceiverNotBetween(String value1, String value2) {
            addCriterion("SmsReceiver not between", value1, value2, "smsReceiver");
            return (Criteria) this;
        }

        public Criteria andResetURLIsNull() {
            addCriterion("ResetURL is null");
            return (Criteria) this;
        }

        public Criteria andResetURLIsNotNull() {
            addCriterion("ResetURL is not null");
            return (Criteria) this;
        }

        public Criteria andResetURLEqualTo(String value) {
            addCriterion("ResetURL =", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLNotEqualTo(String value) {
            addCriterion("ResetURL <>", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLGreaterThan(String value) {
            addCriterion("ResetURL >", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLGreaterThanOrEqualTo(String value) {
            addCriterion("ResetURL >=", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLLessThan(String value) {
            addCriterion("ResetURL <", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLLessThanOrEqualTo(String value) {
            addCriterion("ResetURL <=", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLLike(String value) {
            addCriterion("ResetURL like", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLNotLike(String value) {
            addCriterion("ResetURL not like", value, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLIn(List<String> values) {
            addCriterion("ResetURL in", values, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLNotIn(List<String> values) {
            addCriterion("ResetURL not in", values, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLBetween(String value1, String value2) {
            addCriterion("ResetURL between", value1, value2, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetURLNotBetween(String value1, String value2) {
            addCriterion("ResetURL not between", value1, value2, "resetURL");
            return (Criteria) this;
        }

        public Criteria andResetTipIsNull() {
            addCriterion("ResetTip is null");
            return (Criteria) this;
        }

        public Criteria andResetTipIsNotNull() {
            addCriterion("ResetTip is not null");
            return (Criteria) this;
        }

        public Criteria andResetTipEqualTo(String value) {
            addCriterion("ResetTip =", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipNotEqualTo(String value) {
            addCriterion("ResetTip <>", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipGreaterThan(String value) {
            addCriterion("ResetTip >", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipGreaterThanOrEqualTo(String value) {
            addCriterion("ResetTip >=", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipLessThan(String value) {
            addCriterion("ResetTip <", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipLessThanOrEqualTo(String value) {
            addCriterion("ResetTip <=", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipLike(String value) {
            addCriterion("ResetTip like", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipNotLike(String value) {
            addCriterion("ResetTip not like", value, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipIn(List<String> values) {
            addCriterion("ResetTip in", values, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipNotIn(List<String> values) {
            addCriterion("ResetTip not in", values, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipBetween(String value1, String value2) {
            addCriterion("ResetTip between", value1, value2, "resetTip");
            return (Criteria) this;
        }

        public Criteria andResetTipNotBetween(String value1, String value2) {
            addCriterion("ResetTip not between", value1, value2, "resetTip");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("CreatedAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("CreatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("CreatedAt =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("CreatedAt <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("CreatedAt >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedAt >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("CreatedAt <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("CreatedAt <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("CreatedAt in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("CreatedAt not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("CreatedAt between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("CreatedAt not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("UpdatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("UpdatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("UpdatedAt =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("UpdatedAt <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("UpdatedAt >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdatedAt >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("UpdatedAt <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("UpdatedAt <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("UpdatedAt in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("UpdatedAt not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("UpdatedAt between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("UpdatedAt not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andSimulateIsNull() {
            addCriterion("Simulate is null");
            return (Criteria) this;
        }

        public Criteria andSimulateIsNotNull() {
            addCriterion("Simulate is not null");
            return (Criteria) this;
        }

        public Criteria andSimulateEqualTo(Boolean value) {
            addCriterion("Simulate =", value, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateNotEqualTo(Boolean value) {
            addCriterion("Simulate <>", value, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateGreaterThan(Boolean value) {
            addCriterion("Simulate >", value, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("Simulate >=", value, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateLessThan(Boolean value) {
            addCriterion("Simulate <", value, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateLessThanOrEqualTo(Boolean value) {
            addCriterion("Simulate <=", value, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateIn(List<Boolean> values) {
            addCriterion("Simulate in", values, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateNotIn(List<Boolean> values) {
            addCriterion("Simulate not in", values, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateBetween(Boolean value1, Boolean value2) {
            addCriterion("Simulate between", value1, value2, "simulate");
            return (Criteria) this;
        }

        public Criteria andSimulateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("Simulate not between", value1, value2, "simulate");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNull() {
            addCriterion("TemplateId is null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNotNull() {
            addCriterion("TemplateId is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdEqualTo(Integer value) {
            addCriterion("TemplateId =", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotEqualTo(Integer value) {
            addCriterion("TemplateId <>", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThan(Integer value) {
            addCriterion("TemplateId >", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TemplateId >=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThan(Integer value) {
            addCriterion("TemplateId <", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThanOrEqualTo(Integer value) {
            addCriterion("TemplateId <=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIn(List<Integer> values) {
            addCriterion("TemplateId in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotIn(List<Integer> values) {
            addCriterion("TemplateId not in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdBetween(Integer value1, Integer value2) {
            addCriterion("TemplateId between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TemplateId not between", value1, value2, "templateId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_website
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 12 09:35:14 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_website
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}