package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AlarmWorkOrder;
import com.treefinance.saas.monitor.dao.entity.AlarmWorkOrderCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AlarmWorkOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    long countByExample(AlarmWorkOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int deleteByExample(AlarmWorkOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int insert(AlarmWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int insertSelective(AlarmWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    List<AlarmWorkOrder> selectByExampleWithRowbounds(AlarmWorkOrderCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    List<AlarmWorkOrder> selectByExample(AlarmWorkOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    List<AlarmWorkOrder> selectPaginationByExample(AlarmWorkOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int insertOrUpdateBySelective(AlarmWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    void batchInsert(List<AlarmWorkOrder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AlarmWorkOrder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AlarmWorkOrder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    AlarmWorkOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") AlarmWorkOrder record, @Param("example") AlarmWorkOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int updateByExample(@Param("record") AlarmWorkOrder record, @Param("example") AlarmWorkOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int updateByPrimaryKeySelective(AlarmWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_work_order
     *
     * @mbg.generated Tue May 29 17:39:33 CST 2018
     */
    int updateByPrimaryKey(AlarmWorkOrder record);
}