package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AllOperatorStatDayAccess;
import com.treefinance.saas.monitor.dao.entity.AllOperatorStatDayAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AllOperatorStatDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    long countByExample(AllOperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int deleteByExample(AllOperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int insert(AllOperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int insertSelective(AllOperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    List<AllOperatorStatDayAccess> selectByExampleWithRowbounds(AllOperatorStatDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    List<AllOperatorStatDayAccess> selectByExample(AllOperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    List<AllOperatorStatDayAccess> selectPaginationByExample(AllOperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int insertOrUpdateBySelective(AllOperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    void batchInsert(List<AllOperatorStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    void batchUpdateByPrimaryKey(List<AllOperatorStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<AllOperatorStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    AllOperatorStatDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") AllOperatorStatDayAccess record, @Param("example") AllOperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int updateByExample(@Param("record") AllOperatorStatDayAccess record, @Param("example") AllOperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int updateByPrimaryKeySelective(AllOperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_operator_stat_day_access
     *
     * @mbg.generated Wed Nov 01 13:37:53 CST 2017
     */
    int updateByPrimaryKey(AllOperatorStatDayAccess record);
}