package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.ApiStatMerchantDayAccess;
import com.treefinance.saas.monitor.dao.entity.ApiStatMerchantDayAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ApiStatMerchantDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    long countByExample(ApiStatMerchantDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int deleteByExample(ApiStatMerchantDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int insert(ApiStatMerchantDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int insertSelective(ApiStatMerchantDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    List<ApiStatMerchantDayAccess> selectByExampleWithRowbounds(ApiStatMerchantDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    List<ApiStatMerchantDayAccess> selectByExample(ApiStatMerchantDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    List<ApiStatMerchantDayAccess> selectPaginationByExample(ApiStatMerchantDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int insertOrUpdateBySelective(ApiStatMerchantDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    void batchInsert(List<ApiStatMerchantDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    void batchUpdateByPrimaryKey(List<ApiStatMerchantDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<ApiStatMerchantDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    ApiStatMerchantDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") ApiStatMerchantDayAccess record, @Param("example") ApiStatMerchantDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int updateByExample(@Param("record") ApiStatMerchantDayAccess record, @Param("example") ApiStatMerchantDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int updateByPrimaryKeySelective(ApiStatMerchantDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_stat_merchant_day_access
     *
     * @mbg.generated Fri Jul 07 16:29:56 CST 2017
     */
    int updateByPrimaryKey(ApiStatMerchantDayAccess record);
}