package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmVariable;
import com.treefinance.saas.monitor.dao.entity.AsAlarmVariableCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmVariableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    long countByExample(AsAlarmVariableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int deleteByExample(AsAlarmVariableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int insert(AsAlarmVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int insertSelective(AsAlarmVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    List<AsAlarmVariable> selectByExampleWithRowbounds(AsAlarmVariableCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    List<AsAlarmVariable> selectByExample(AsAlarmVariableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    List<AsAlarmVariable> selectPaginationByExample(AsAlarmVariableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    void batchInsert(List<AsAlarmVariable> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmVariable> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmVariable> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    AsAlarmVariable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmVariable record, @Param("example") AsAlarmVariableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmVariable record, @Param("example") AsAlarmVariableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_variable
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByPrimaryKey(AsAlarmVariable record);
}