package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmMsg;
import com.treefinance.saas.monitor.dao.entity.AsAlarmMsgCriteria;
import com.treefinance.saas.monitor.dao.entity.AsAlarmMsgWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    long countByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int deleteByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int insert(AsAlarmMsgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int insertSelective(AsAlarmMsgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmMsgWithBLOBs> selectByExampleWithBLOBsWithRowbounds(AsAlarmMsgCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmMsgWithBLOBs> selectByExampleWithBLOBs(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmMsg> selectByExampleWithRowbounds(AsAlarmMsgCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmMsg> selectByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmMsg> selectPaginationByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmMsgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    void batchInsert(List<AsAlarmMsgWithBLOBs> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmMsg> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmMsg> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    AsAlarmMsgWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmMsgWithBLOBs record, @Param("example") AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AsAlarmMsgWithBLOBs record, @Param("example") AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmMsg record, @Param("example") AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmMsgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AsAlarmMsgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByPrimaryKey(AsAlarmMsg record);
}