package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmNotify;
import com.treefinance.saas.monitor.dao.entity.AsAlarmNotifyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmNotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    long countByExample(AsAlarmNotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int deleteByExample(AsAlarmNotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int insert(AsAlarmNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int insertSelective(AsAlarmNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    List<AsAlarmNotify> selectByExampleWithRowbounds(AsAlarmNotifyCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    List<AsAlarmNotify> selectByExample(AsAlarmNotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    List<AsAlarmNotify> selectPaginationByExample(AsAlarmNotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    void batchInsert(List<AsAlarmNotify> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmNotify> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmNotify> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    AsAlarmNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmNotify record, @Param("example") AsAlarmNotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmNotify record, @Param("example") AsAlarmNotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_notify
     *
     * @mbg.generated Tue Jul 24 11:31:38 CST 2018
     */
    int updateByPrimaryKey(AsAlarmNotify record);
}