package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmMsg;
import com.treefinance.saas.monitor.dao.entity.AsAlarmMsgCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    long countByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int deleteByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int insert(AsAlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int insertSelective(AsAlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    List<AsAlarmMsg> selectByExampleWithRowbounds(AsAlarmMsgCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    List<AsAlarmMsg> selectByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    List<AsAlarmMsg> selectPaginationByExample(AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    void batchInsert(List<AsAlarmMsg> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmMsg> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmMsg> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    AsAlarmMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmMsg record, @Param("example") AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmMsg record, @Param("example") AsAlarmMsgCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_msg
     *
     * @mbg.generated Mon Jul 23 20:30:06 CST 2018
     */
    int updateByPrimaryKey(AsAlarmMsg record);
}