package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmTrigger;
import com.treefinance.saas.monitor.dao.entity.AsAlarmTriggerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmTriggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    long countByExample(AsAlarmTriggerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int deleteByExample(AsAlarmTriggerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int insert(AsAlarmTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int insertSelective(AsAlarmTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmTrigger> selectByExampleWithRowbounds(AsAlarmTriggerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmTrigger> selectByExample(AsAlarmTriggerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    List<AsAlarmTrigger> selectPaginationByExample(AsAlarmTriggerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    void batchInsert(List<AsAlarmTrigger> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmTrigger> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmTrigger> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    AsAlarmTrigger selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmTrigger record, @Param("example") AsAlarmTriggerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmTrigger record, @Param("example") AsAlarmTriggerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmTrigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_trigger
     *
     * @mbg.generated Wed Jul 18 19:57:44 CST 2018
     */
    int updateByPrimaryKey(AsAlarmTrigger record);
}