package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmQuery;
import com.treefinance.saas.monitor.dao.entity.AsAlarmQueryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmQueryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    long countByExample(AsAlarmQueryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int deleteByExample(AsAlarmQueryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int insert(AsAlarmQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int insertSelective(AsAlarmQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    List<AsAlarmQuery> selectByExampleWithRowbounds(AsAlarmQueryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    List<AsAlarmQuery> selectByExample(AsAlarmQueryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    List<AsAlarmQuery> selectPaginationByExample(AsAlarmQueryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    void batchInsert(List<AsAlarmQuery> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmQuery> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmQuery> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    AsAlarmQuery selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmQuery record, @Param("example") AsAlarmQueryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmQuery record, @Param("example") AsAlarmQueryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_query
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByPrimaryKey(AsAlarmQuery record);
}