package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsAlarmConstant;
import com.treefinance.saas.monitor.dao.entity.AsAlarmConstantCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsAlarmConstantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    long countByExample(AsAlarmConstantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int deleteByExample(AsAlarmConstantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int insert(AsAlarmConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int insertSelective(AsAlarmConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    List<AsAlarmConstant> selectByExampleWithRowbounds(AsAlarmConstantCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    List<AsAlarmConstant> selectByExample(AsAlarmConstantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    List<AsAlarmConstant> selectPaginationByExample(AsAlarmConstantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int insertOrUpdateBySelective(AsAlarmConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    void batchInsert(List<AsAlarmConstant> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsAlarmConstant> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsAlarmConstant> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    AsAlarmConstant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsAlarmConstant record, @Param("example") AsAlarmConstantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByExample(@Param("record") AsAlarmConstant record, @Param("example") AsAlarmConstantCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByPrimaryKeySelective(AsAlarmConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_alarm_constant
     *
     * @mbg.generated Thu Jul 19 14:02:23 CST 2018
     */
    int updateByPrimaryKey(AsAlarmConstant record);
}