package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsStatCallback;
import com.treefinance.saas.monitor.dao.entity.AsStatCallbackCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AsStatCallbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    long countByExample(AsStatCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int deleteByExample(AsStatCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int insert(AsStatCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int insertSelective(AsStatCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    List<AsStatCallback> selectByExampleWithRowbounds(AsStatCallbackCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    List<AsStatCallback> selectByExample(AsStatCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    List<AsStatCallback> selectPaginationByExample(AsStatCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int insertOrUpdateBySelective(AsStatCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    void batchInsert(List<AsStatCallback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsStatCallback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsStatCallback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    AsStatCallback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsStatCallback record, @Param("example") AsStatCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByExample(@Param("record") AsStatCallback record, @Param("example") AsStatCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByPrimaryKeySelective(AsStatCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByPrimaryKey(AsStatCallback record);
}