package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.AsStatDayCallback;
import com.treefinance.saas.monitor.dao.entity.AsStatDayCallbackCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AsStatDayCallbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    long countByExample(AsStatDayCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int deleteByExample(AsStatDayCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int insert(AsStatDayCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int insertSelective(AsStatDayCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    List<AsStatDayCallback> selectByExampleWithRowbounds(AsStatDayCallbackCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    List<AsStatDayCallback> selectByExample(AsStatDayCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    List<AsStatDayCallback> selectPaginationByExample(AsStatDayCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int insertOrUpdateBySelective(AsStatDayCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    void batchInsert(List<AsStatDayCallback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    void batchUpdateByPrimaryKey(List<AsStatDayCallback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<AsStatDayCallback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    AsStatDayCallback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") AsStatDayCallback record, @Param("example") AsStatDayCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByExample(@Param("record") AsStatDayCallback record, @Param("example") AsStatDayCallbackCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByPrimaryKeySelective(AsStatDayCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_day_callback
     *
     * @mbg.generated Thu Mar 15 14:23:22 CST 2018
     */
    int updateByPrimaryKey(AsStatDayCallback record);
}