package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.Bank;
import com.treefinance.saas.monitor.dao.entity.BankCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int countByExample(BankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int deleteByExample(BankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int insert(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int insertSelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    List<Bank> selectByExampleWithRowbounds(BankCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    List<Bank> selectByExample(BankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") Bank record, @Param("example") BankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByExample(@Param("record") Bank record, @Param("example") BankCriteria example);
}