package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.BasicData;
import com.treefinance.saas.monitor.dao.entity.BasicDataCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface BasicDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    long countByExample(BasicDataCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int deleteByExample(BasicDataCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int insert(BasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int insertSelective(BasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    List<BasicData> selectByExampleWithRowbounds(BasicDataCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    List<BasicData> selectByExample(BasicDataCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    List<BasicData> selectPaginationByExample(BasicDataCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int insertOrUpdateBySelective(BasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    void batchInsert(List<BasicData> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    void batchUpdateByPrimaryKey(List<BasicData> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<BasicData> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    BasicData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") BasicData record, @Param("example") BasicDataCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int updateByExample(@Param("record") BasicData record, @Param("example") BasicDataCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int updateByPrimaryKeySelective(BasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_basic_data
     *
     * @mbg.generated Tue Apr 24 17:41:25 CST 2018
     */
    int updateByPrimaryKey(BasicData record);
}