package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.Ecommerce;
import com.treefinance.saas.monitor.dao.entity.EcommerceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EcommerceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int countByExample(EcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int deleteByExample(EcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int insert(Ecommerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int insertSelective(Ecommerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    List<Ecommerce> selectByExampleWithRowbounds(EcommerceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    List<Ecommerce> selectByExample(EcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") Ecommerce record, @Param("example") EcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ecommerce
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByExample(@Param("record") Ecommerce record, @Param("example") EcommerceCriteria example);
}