package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.EmailStatDayAccess;
import com.treefinance.saas.monitor.dao.entity.EmailStatDayAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmailStatDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    long countByExample(EmailStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int deleteByExample(EmailStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int insert(EmailStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int insertSelective(EmailStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    List<EmailStatDayAccess> selectByExampleWithRowbounds(EmailStatDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    List<EmailStatDayAccess> selectByExample(EmailStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    List<EmailStatDayAccess> selectPaginationByExample(EmailStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int insertOrUpdateBySelective(EmailStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    void batchInsert(List<EmailStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    void batchUpdateByPrimaryKey(List<EmailStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<EmailStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    EmailStatDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") EmailStatDayAccess record, @Param("example") EmailStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int updateByExample(@Param("record") EmailStatDayAccess record, @Param("example") EmailStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int updateByPrimaryKeySelective(EmailStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_stat_day_access
     *
     * @mbg.generated Fri Mar 09 16:00:22 CST 2018
     */
    int updateByPrimaryKey(EmailStatDayAccess record);
}