package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.MerchantStatAccess;
import com.treefinance.saas.monitor.dao.entity.MerchantStatAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantStatAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int countByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int deleteByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int insert(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int insertSelective(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    List<MerchantStatAccess> selectByExampleWithRowbounds(MerchantStatAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    List<MerchantStatAccess> selectByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    MerchantStatAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantStatAccess record, @Param("example") MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByExample(@Param("record") MerchantStatAccess record, @Param("example") MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByPrimaryKey(MerchantStatAccess record);
}