package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.MerchantStatAccess;
import com.treefinance.saas.monitor.dao.entity.MerchantStatAccessCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MerchantStatAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    long countByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int deleteByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int insert(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int insertSelective(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    List<MerchantStatAccess> selectByExampleWithRowbounds(MerchantStatAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    List<MerchantStatAccess> selectByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    List<MerchantStatAccess> selectPaginationByExample(MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int insertOrUpdateBySelective(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    void batchInsert(List<MerchantStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    void batchUpdateByPrimaryKey(List<MerchantStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<MerchantStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    MerchantStatAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") MerchantStatAccess record, @Param("example") MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int updateByExample(@Param("record") MerchantStatAccess record, @Param("example") MerchantStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int updateByPrimaryKeySelective(MerchantStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_access
     *
     * @mbg.generated Wed Apr 04 16:02:20 CST 2018
     */
    int updateByPrimaryKey(MerchantStatAccess record);
}