package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.MerchantStatBank;
import com.treefinance.saas.monitor.dao.entity.MerchantStatBankCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MerchantStatBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int countByExample(MerchantStatBankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int deleteByExample(MerchantStatBankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int insert(MerchantStatBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int insertSelective(MerchantStatBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    List<MerchantStatBank> selectByExampleWithRowbounds(MerchantStatBankCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    List<MerchantStatBank> selectByExample(MerchantStatBankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    MerchantStatBank selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantStatBank record, @Param("example") MerchantStatBankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByExample(@Param("record") MerchantStatBank record, @Param("example") MerchantStatBankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantStatBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_bank
     *
     * @mbggenerated Wed Jun 14 17:16:27 CST 2017
     */
    int updateByPrimaryKey(MerchantStatBank record);
}