package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.MerchantAccessHistory;
import com.treefinance.saas.monitor.dao.entity.MerchantAccessHistoryCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MerchantAccessHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int countByExample(MerchantAccessHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int deleteByExample(MerchantAccessHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int insert(MerchantAccessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int insertSelective(MerchantAccessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    List<MerchantAccessHistory> selectByExampleWithRowbounds(MerchantAccessHistoryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    List<MerchantAccessHistory> selectByExample(MerchantAccessHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    MerchantAccessHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantAccessHistory record, @Param("example") MerchantAccessHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int updateByExample(@Param("record") MerchantAccessHistory record, @Param("example") MerchantAccessHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantAccessHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_access_history
     *
     * @mbggenerated Thu Jun 22 13:44:43 CST 2017
     */
    int updateByPrimaryKey(MerchantAccessHistory record);
}