package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.MerchantStatDayAccess;
import com.treefinance.saas.monitor.dao.entity.MerchantStatDayAccessCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MerchantStatDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    long countByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int deleteByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int insert(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int insertSelective(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    List<MerchantStatDayAccess> selectByExampleWithRowbounds(MerchantStatDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    List<MerchantStatDayAccess> selectByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    List<MerchantStatDayAccess> selectPaginationByExample(MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int insertOrUpdateBySelective(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    void batchInsert(List<MerchantStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    void batchUpdateByPrimaryKey(List<MerchantStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<MerchantStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    MerchantStatDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") MerchantStatDayAccess record, @Param("example") MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int updateByExample(@Param("record") MerchantStatDayAccess record, @Param("example") MerchantStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int updateByPrimaryKeySelective(MerchantStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_day_access
     *
     * @mbg.generated Wed Apr 04 16:02:19 CST 2018
     */
    int updateByPrimaryKey(MerchantStatDayAccess record);
}