package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.MerchantStatEcommerce;
import com.treefinance.saas.monitor.dao.entity.MerchantStatEcommerceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MerchantStatEcommerceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int countByExample(MerchantStatEcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int deleteByExample(MerchantStatEcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int insert(MerchantStatEcommerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int insertSelective(MerchantStatEcommerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    List<MerchantStatEcommerce> selectByExampleWithRowbounds(MerchantStatEcommerceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    List<MerchantStatEcommerce> selectByExample(MerchantStatEcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    MerchantStatEcommerce selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantStatEcommerce record, @Param("example") MerchantStatEcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByExample(@Param("record") MerchantStatEcommerce record, @Param("example") MerchantStatEcommerceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantStatEcommerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_stat_ecommerce
     *
     * @mbggenerated Thu Jun 08 13:58:11 CST 2017
     */
    int updateByPrimaryKey(MerchantStatEcommerce record);
}