package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.OperatorStatDayAccess;
import com.treefinance.saas.monitor.dao.entity.OperatorStatDayAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OperatorStatDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    long countByExample(OperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int deleteByExample(OperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int insert(OperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int insertSelective(OperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    List<OperatorStatDayAccess> selectByExampleWithRowbounds(OperatorStatDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    List<OperatorStatDayAccess> selectByExample(OperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    List<OperatorStatDayAccess> selectPaginationByExample(OperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int insertOrUpdateBySelective(OperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    void batchInsert(List<OperatorStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    void batchUpdateByPrimaryKey(List<OperatorStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<OperatorStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    OperatorStatDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") OperatorStatDayAccess record, @Param("example") OperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int updateByExample(@Param("record") OperatorStatDayAccess record, @Param("example") OperatorStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int updateByPrimaryKeySelective(OperatorStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_day_access
     *
     * @mbg.generated Tue Nov 14 16:07:59 CST 2017
     */
    int updateByPrimaryKey(OperatorStatDayAccess record);
}