package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.Operator;
import com.treefinance.saas.monitor.dao.entity.OperatorCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    int countByExample(OperatorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    int deleteByExample(OperatorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    List<Operator> selectByExampleWithRowbounds(OperatorCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    List<Operator> selectByExample(OperatorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") Operator record, @Param("example") OperatorCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator
     *
     * @mbggenerated Mon Jun 12 09:35:14 CST 2017
     */
    int updateByExample(@Param("record") Operator record, @Param("example") OperatorCriteria example);
}