package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.OperatorAllStatAccess;
import com.treefinance.saas.monitor.dao.entity.OperatorAllStatAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OperatorAllStatAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    long countByExample(OperatorAllStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int deleteByExample(OperatorAllStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int insert(OperatorAllStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int insertSelective(OperatorAllStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    List<OperatorAllStatAccess> selectByExampleWithRowbounds(OperatorAllStatAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    List<OperatorAllStatAccess> selectByExample(OperatorAllStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    List<OperatorAllStatAccess> selectPaginationByExample(OperatorAllStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int insertOrUpdateBySelective(OperatorAllStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    void batchInsert(List<OperatorAllStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    void batchUpdateByPrimaryKey(List<OperatorAllStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<OperatorAllStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    OperatorAllStatAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") OperatorAllStatAccess record, @Param("example") OperatorAllStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int updateByExample(@Param("record") OperatorAllStatAccess record, @Param("example") OperatorAllStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int updateByPrimaryKeySelective(OperatorAllStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_all_stat_access
     *
     * @mbg.generated Tue Apr 17 17:21:18 CST 2018
     */
    int updateByPrimaryKey(OperatorAllStatAccess record);
}