package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.OperatorStatAccess;
import com.treefinance.saas.monitor.dao.entity.OperatorStatAccessCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface OperatorStatAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    long countByExample(OperatorStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int deleteByExample(OperatorStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int insert(OperatorStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int insertSelective(OperatorStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    List<OperatorStatAccess> selectByExampleWithRowbounds(OperatorStatAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    List<OperatorStatAccess> selectByExample(OperatorStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    List<OperatorStatAccess> selectPaginationByExample(OperatorStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int insertOrUpdateBySelective(OperatorStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    void batchInsert(List<OperatorStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    void batchUpdateByPrimaryKey(List<OperatorStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<OperatorStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    OperatorStatAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") OperatorStatAccess record, @Param("example") OperatorStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int updateByExample(@Param("record") OperatorStatAccess record, @Param("example") OperatorStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int updateByPrimaryKeySelective(OperatorStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_stat_access
     *
     * @mbg.generated Sun Apr 08 19:26:46 CST 2018
     */
    int updateByPrimaryKey(OperatorStatAccess record);
}