package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.RealTimeStatAccess;
import com.treefinance.saas.monitor.dao.entity.RealTimeStatAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RealTimeStatAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    long countByExample(RealTimeStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int deleteByExample(RealTimeStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int insert(RealTimeStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int insertSelective(RealTimeStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    List<RealTimeStatAccess> selectByExampleWithRowbounds(RealTimeStatAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    List<RealTimeStatAccess> selectByExample(RealTimeStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    List<RealTimeStatAccess> selectPaginationByExample(RealTimeStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int insertOrUpdateBySelective(RealTimeStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    void batchInsert(List<RealTimeStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    void batchUpdateByPrimaryKey(List<RealTimeStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<RealTimeStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    RealTimeStatAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") RealTimeStatAccess record, @Param("example") RealTimeStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int updateByExample(@Param("record") RealTimeStatAccess record, @Param("example") RealTimeStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int updateByPrimaryKeySelective(RealTimeStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table real_time_stat_access
     *
     * @mbg.generated Thu Jun 21 16:20:58 CST 2018
     */
    int updateByPrimaryKey(RealTimeStatAccess record);
}