package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.SaasErrorStepDayStat;
import com.treefinance.saas.monitor.dao.entity.SaasErrorStepDayStatCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SaasErrorStepDayStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    long countByExample(SaasErrorStepDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int deleteByExample(SaasErrorStepDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int insert(SaasErrorStepDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int insertSelective(SaasErrorStepDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    List<SaasErrorStepDayStat> selectByExampleWithRowbounds(SaasErrorStepDayStatCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    List<SaasErrorStepDayStat> selectByExample(SaasErrorStepDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    List<SaasErrorStepDayStat> selectPaginationByExample(SaasErrorStepDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int insertOrUpdateBySelective(SaasErrorStepDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    void batchInsert(List<SaasErrorStepDayStat> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    void batchUpdateByPrimaryKey(List<SaasErrorStepDayStat> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<SaasErrorStepDayStat> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    SaasErrorStepDayStat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") SaasErrorStepDayStat record, @Param("example") SaasErrorStepDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int updateByExample(@Param("record") SaasErrorStepDayStat record, @Param("example") SaasErrorStepDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int updateByPrimaryKeySelective(SaasErrorStepDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_step_day_stat
     *
     * @mbg.generated Wed Aug 23 13:49:15 CST 2017
     */
    int updateByPrimaryKey(SaasErrorStepDayStat record);
}