package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.SaasErrorDayStat;
import com.treefinance.saas.monitor.dao.entity.SaasErrorDayStatCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SaasErrorDayStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    long countByExample(SaasErrorDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int deleteByExample(SaasErrorDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int insert(SaasErrorDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int insertSelective(SaasErrorDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    List<SaasErrorDayStat> selectByExampleWithRowbounds(SaasErrorDayStatCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    List<SaasErrorDayStat> selectByExample(SaasErrorDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    List<SaasErrorDayStat> selectPaginationByExample(SaasErrorDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int insertOrUpdateBySelective(SaasErrorDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    void batchInsert(List<SaasErrorDayStat> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    void batchUpdateByPrimaryKey(List<SaasErrorDayStat> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<SaasErrorDayStat> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    SaasErrorDayStat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") SaasErrorDayStat record, @Param("example") SaasErrorDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int updateByExample(@Param("record") SaasErrorDayStat record, @Param("example") SaasErrorDayStatCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int updateByPrimaryKeySelective(SaasErrorDayStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_error_day_stat
     *
     * @mbg.generated Tue Aug 22 16:40:50 CST 2017
     */
    int updateByPrimaryKey(SaasErrorDayStat record);
}