package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.SaasStatDayAccess;
import com.treefinance.saas.monitor.dao.entity.SaasStatDayAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SaasStatDayAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    long countByExample(SaasStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int deleteByExample(SaasStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int insert(SaasStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int insertSelective(SaasStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    List<SaasStatDayAccess> selectByExampleWithRowbounds(SaasStatDayAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    List<SaasStatDayAccess> selectByExample(SaasStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    List<SaasStatDayAccess> selectPaginationByExample(SaasStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int insertOrUpdateBySelective(SaasStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    void batchInsert(List<SaasStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    void batchUpdateByPrimaryKey(List<SaasStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<SaasStatDayAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    SaasStatDayAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") SaasStatDayAccess record, @Param("example") SaasStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByExample(@Param("record") SaasStatDayAccess record, @Param("example") SaasStatDayAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByPrimaryKeySelective(SaasStatDayAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_day_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByPrimaryKey(SaasStatDayAccess record);
}