package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.SaasStatAccess;
import com.treefinance.saas.monitor.dao.entity.SaasStatAccessCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SaasStatAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    long countByExample(SaasStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int deleteByExample(SaasStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int insert(SaasStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int insertSelective(SaasStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    List<SaasStatAccess> selectByExampleWithRowbounds(SaasStatAccessCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    List<SaasStatAccess> selectByExample(SaasStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    List<SaasStatAccess> selectPaginationByExample(SaasStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int insertOrUpdateBySelective(SaasStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    void batchInsert(List<SaasStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    void batchUpdateByPrimaryKey(List<SaasStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<SaasStatAccess> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    SaasStatAccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") SaasStatAccess record, @Param("example") SaasStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByExample(@Param("record") SaasStatAccess record, @Param("example") SaasStatAccessCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByPrimaryKeySelective(SaasStatAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saas_stat_access
     *
     * @mbg.generated Fri Aug 04 16:42:37 CST 2017
     */
    int updateByPrimaryKey(SaasStatAccess record);
}