package com.treefinance.saas.monitor.dao.mapper;

import com.treefinance.saas.monitor.dao.entity.StatTemplate;
import com.treefinance.saas.monitor.dao.entity.StatTemplateCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StatTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    long countByExample(StatTemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int deleteByExample(StatTemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int insert(StatTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int insertSelective(StatTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    List<StatTemplate> selectByExampleWithRowbounds(StatTemplateCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    List<StatTemplate> selectByExample(StatTemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    List<StatTemplate> selectPaginationByExample(StatTemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int insertOrUpdateBySelective(StatTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    void batchInsert(List<StatTemplate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    void batchUpdateByPrimaryKey(List<StatTemplate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    void batchUpdateByPrimaryKeySelective(List<StatTemplate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    StatTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") StatTemplate record, @Param("example") StatTemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int updateByExample(@Param("record") StatTemplate record, @Param("example") StatTemplateCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int updateByPrimaryKeySelective(StatTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_stat_template
     *
     * @mbg.generated Mon Jan 22 21:34:16 CST 2018
     */
    int updateByPrimaryKey(StatTemplate record);
}